### ISSUE TITLE
Just playlist?

### ISSUE THREAD

**Issue by Cluuey** [SleekPanther/youtube-chronological-order#3]
I've just found your extension as I'm trying to watch things in order and, as you're aware, YouTube is terrible for this.
I was using PlaybackLoop but they've stopped that working too.

Is it possible to reverse just a playlist instead of all of the videos a channel uploads?

In my case I'm trying to catch up on the WoW pre-expansion videos but they upload lots of other videos too, when I pressed **Alt+P** my next video ended up being something I didn't want to watch, so I went looking for more information, or alternatives, and found out it just works this way.

I had pondered trying to use Tampermonkey to try but I'm not cluey enough to work that out. 😢

**Comment by SleekPanther** [comment]
Try [Improve Youtube](https://chrome.google.com/webstore/detail/improve-youtube-open-sour/bnomihfieiccainjcjblhegjgglakjdd)
Click the extension icon then go to Playlist and enable the **Reverse** slider 
![image](https://user-images.githubusercontent.com/15304528/100032487-2441d200-2dc6-11eb-9663-9a411683d2ca.png)

Then you'll see a new icon on the watch page of a playlist
![image](https://user-images.githubusercontent.com/15304528/100032638-74209900-2dc6-11eb-9803-e1e39398faef.png)

Others have also recommended [Iridium for YouTube](https://chrome.google.com/webstore/detail/iridium-for-youtube/gbjmgndncjkjfcnpfhgidhbgokofegbl) which I haven't tried myself
